import { useEffect,useState } from 'react';
import ClientShell from '../../../components/client/ClientShell/ClientShell';
import { clientPortal } from '../../../services/supabase/clientPortal';
import { getStoredSession } from '../../../services/supabase/supabaseClient';
import { getErrorMessage } from '../../../services/errors/errorMessages';
import { ButtonSpinner, PageLoader, useToast } from '../../../components/ui/Feedback/Feedback';
const money=(n,c='RSD')=>new Intl.NumberFormat('sr-RS',{style:'currency',currency:c}).format((n||0)/100);
export default function OffersPage(){
 const [items,setItems]=useState([]),[error,setError]=useState(''),[busy,setBusy]=useState(''),[promo,setPromo]=useState({}),[loading,setLoading]=useState(true); const toast=useToast();
 useEffect(()=>{let alive=true; clientPortal.offerings().then(x=>{if(alive)setItems(x)}).catch(e=>{if(alive)setError(getErrorMessage(e))}).finally(()=>{if(alive)setLoading(false)}); return()=>{alive=false}},[]);
 const buy=async item=>{setBusy(item.id);setError('');try{const r=await clientPortal.createOrder(item.id,promo[item.id]||null);if(r.order?.total_amount===0){toast.success('Pristup je aktiviran.');window.history.pushState({},'','/nalog');window.dispatchEvent(new PopStateEvent('popstate'));}else toast.success('Porudžbina je kreirana. Plaćanje ćemo povezati sa payment providerom.');}catch(e){const m=getErrorMessage(e);setError(m);toast.error(m)}finally{setBusy('')}};
 return <ClientShell email={getStoredSession()?.user?.email}>{loading?<PageLoader label="Učitavamo ponudu..."/>:<><div className="client-page-head"><p className="kicker">PONUDA</p><h1>Izaberi svoj sledeći korak.</h1></div>{error&&<p className="client-error">{error}</p>}<div className="client-grid">{items.map(i=>{const p=i.offering_prices?.[0];return <article className="client-card" key={i.id}><span className="client-pill">{i.type}</span><h2>{i.title}</h2><p>{i.short_description||i.description}</p><h3>{p?money(p.amount,p.currency):'Cena na upit'}</h3>{p&&<div className="client-form"><label>Promo kod<input value={promo[i.id]||''} onChange={e=>setPromo(v=>({...v,[i.id]:e.target.value.toUpperCase()}))} placeholder="Opcionalno"/></label><button className="client-btn" disabled={busy===i.id} onClick={()=>buy(i)}>{busy===i.id&&<ButtonSpinner/>}{busy===i.id?'Obrađujemo...':'Nastavi'}</button></div>}</article>})}{!items.length&&!error&&<p className="client-empty">Trenutno nema dostupnih ponuda.</p>}</div></>}</ClientShell>}
