import { useEffect,useState } from 'react';
import ClientShell from '../../../components/client/ClientShell/ClientShell';
import { clientPortal } from '../../../services/supabase/clientPortal';
import { getErrorMessage } from '../../../services/errors/errorMessages';
import { ConfirmDialog, PageLoader, useToast } from '../../../components/ui/Feedback/Feedback';
const money=(n,c='RSD')=>new Intl.NumberFormat('sr-RS',{style:'currency',currency:c}).format((n||0)/100);
export default function DashboardPage(){const [data,setData]=useState(null),[error,setError]=useState(''),[cancel,setCancel]=useState(null),[cancelling,setCancelling]=useState(false);const toast=useToast();
 useEffect(()=>{let alive=true;clientPortal.dashboard().then(d=>alive&&setData(d)).catch(e=>alive&&setError(getErrorMessage(e)));return()=>{alive=false}},[]);
 const confirmCancel=async()=>{if(!cancel)return;setCancelling(true);try{await clientPortal.cancelSubscription(cancel.id);setData(await clientPortal.dashboard());toast.success('Pretplata će biti otkazana na kraju perioda.');setCancel(null)}catch(e){const m=getErrorMessage(e);setError(m);toast.error(m)}finally{setCancelling(false)}};
 return <ClientShell email={data?.email}>{!data&&!error?<PageLoader label="Učitavamo tvoj nalog..."/>:<><div className="client-page-head"><p className="kicker">MOJ PROSTOR</p><h1>{data?.profile?.first_name?`Zdravo, ${data.profile.first_name}.`:'Tvoj pregled.'}</h1><p>Na jednom mestu: pristupi, pretplate i porudžbine.</p></div>{error&&<p className="client-error">{error}</p>}{data&&<div className="client-grid"><section className="client-card"><h2>Moji pristupi</h2>{data.access.length?data.access.map(x=><div className="client-row" key={x.id}><span>{x.offerings?.title||'Usluga'}</span><span className="client-pill">{x.offerings?.type}</span></div>):<p className="client-empty">Još nema aktivnih pristupa.</p>}</section><section className="client-card"><h2>Pretplate</h2>{data.subscriptions.length?data.subscriptions.map(x=><div className="client-row" key={x.id}><div><strong>{x.offerings?.title||'Pretplata'}</strong><br/><small>{x.cancel_at_period_end?'Otkazuje se na kraju perioda':x.status}</small></div>{!x.cancel_at_period_end&&<button className="client-btn secondary" onClick={()=>setCancel(x)}>Otkaži</button>}</div>):<p className="client-empty">Nema aktivnih pretplata.</p>}</section><section className="client-card" style={{gridColumn:'1/-1'}}><h2>Poslednje porudžbine</h2>{data.orders.length?data.orders.map(o=><div className="client-row" key={o.id}><div><strong>{o.order_number}</strong><br/><small>{new Date(o.created_at).toLocaleDateString('sr-RS')}</small></div><div>{money(o.total_amount,o.currency)} · <span className="client-pill">{o.status}</span></div></div>):<p className="client-empty">Još nema porudžbina.</p>}</section></div>}</>}
 <ConfirmDialog open={!!cancel} title="Otkazati pretplatu?" message="Pretplata će ostati aktivna do kraja već plaćenog perioda, a zatim se neće obnoviti." confirmLabel="Otkaži pretplatu" danger busy={cancelling} onCancel={()=>!cancelling&&setCancel(null)} onConfirm={confirmCancel}/></ClientShell>}
